### PR TITLE
Fix attributions for Jonathan Penny and Matt Simpson

### LINKED ISSUE #23: Fix attributions
Jonathan Penny and Matt Simpson have changed organisations.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Closes #23 .

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/adpt/pull/24.html" title="Last updated on May 29, 2020, 2:07 PM UTC (7dac80c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/adpt/24/21fc379...7dac80c.html" title="Last updated on May 29, 2020, 2:07 PM UTC (7dac80c)">Diff</a>

### CODE REVIEW

**Comment by matt-cutnpaste** [comment]
Looks good to me!

**Review by matt-cutnpaste — APPROVED** [review]
That looks correct to me!

**Review by matt-cutnpaste — APPROVED** [review]
That looks correct to me!

**Comment by nigelmegitt** [comment]
I also got independent confirmation from Jonathan Penny that he is happy with this change (he has no GitHub user).

**Pull request merged**
